---

- name: deploy systemd
  include_role:
    name: systemd
  vars:
    this_role_name: "cm_db_{{ cm_db_port }}"
    service_name: "cm_db-{{ cm_db_port }}"
    service_type: "{{ deployment_method }}" 
