---

- name: restart alpha
  systemd: name=alpha-{{ alpha_port }} state=restarted daemon_reload=yes enabled=yes

- name: wait for service port is up
  wait_for:
    port: "{{ alpha_port }}"
    state: started
    msg: "the service port {{ alpha_port }} is not up"

