---

# stop mgmt
- name: stop mgmt
  uri:
    url: "{{ cm_api_url }}/cm/service/commands/stop"
    method: POST
    body_format: json
    status_code: 200
    user: "{{ cloudera_management_default_user }}"
    password: "{{ cloudera_management_default_pass }}"
    force_basic_auth: yes
    return_content: yes
  register: stop_mgmt
  until: stop_mgmt['json']['active']  == true
  retries: 10
  delay: 3
  when: "inventory_hostname_short in groups['cm_server_node']"

# stop agent
- block:
  - name: stop cloudera-scm-agent
    systemd: name=supervisord state=stopped
  
  - name: wait until the cm-agent port is down
    wait_for:
      port: 9001
      state: stopped
      msg: "the cm-agent port 9001 is not down"
  when: "inventory_hostname_short in groups['cm_agent_node']"

# stop server
- block:
  - name: start cloudera-scm-server
    systemd: name=cloudera-scm-server state=stopped
  
  - name: wait until the cm-server web port is up
    wait_for:
      port: 7180
      state: stopped
      msg: "the cm-server web port 7180 is up"
  when: "inventory_hostname_short in groups['cm_server_node']"

# change dir
- name: change data and log dir
  script: change_dir.sh

# start server
- block:
  - name: start cloudera-scm-server
    systemd: name=cloudera-scm-server state=stopped
  
  - name: wait until the cm-server web port is up
    wait_for:
      port: 7180
      state: started
      msg: "the cm-server web port 7180 is up"
  when: "inventory_hostname_short in groups['cm_server_node']"

# start agent
- block:
  - name: start cloudera-scm-agent
    systemd: name=cloudera-scm-agent state=started
  
  - name: wait until the cm-agent port is up
    wait_for:
      port: 9001
      state: started
      msg: "the cm-agent port 9001 is up"
  when: "inventory_hostname_short in groups['cm_agent_node']"

# start mgmt
- name: start mgmt
  uri:
    url: "{{ cm_api_url }}/cm/service/commands/start"
    method: POST
    body_format: json
    status_code: 200
    user: "{{ cloudera_management_default_user }}"
    password: "{{ cloudera_management_default_pass }}"
    force_basic_auth: yes
    return_content: yes
  register: stop_mgmt
  until: stop_mgmt['json']['active']  == true
  retries: 10
  delay: 3
  when: "inventory_hostname_short in groups['cm_server_node']"
