---

local_download_dir: "{{ playbook_dir }}/download"
local_resource_dir: "{{ playbook_dir }}/resource"
local_binary_dir: "{{ playbook_dir }}/resource/bin"
local_conf_dir: "{{ playbook_dir }}/conf"

download_type: image

# urls
flannel_image_repo: "quay.io/coreos"
kubernetes_image_repo: "registry.aliyuncs.com/google_containers"

# versions
kube_vip_version: 0.1.1
pause_version: 3.1
etcd_version: 3.3.15-0
kube_version: v1.16.0
flannel_version: v0.12.0-amd64
coredns_version: 1.6.2

# names
names:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kube-proxy
