---

# start server
- name: start cloudera-scm-server
  systemd: name=cloudera-scm-server state=started

- name: wait until the cm-server web port is up
  wait_for:
    port: 7180
    state: started
    msg: "the cm-server web port 7180 is up"
