---

- name: unarchive binary packages
  unarchive:
    src: "{{ local_download_dir }}/{{ item }}"
    dest: "{{ ratel_bin_dir }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  loop: "{{ binary_names }}"

- name: create run script
  template:
    src: "run_{{ role_name }}_binary.sh.j2"
    dest: "{{ script_dir }}/run_{{ role_name }}_{{ ratel_port }}.sh"
    owner: "{{ ratel_user }}"
    group: "{{ ratel_user }}"
    mode: "0755"
    backup: yes
  with_items:
    - run

- include_tasks: "{{ process_supervision_method }}_supervision.yml"
