---

# prepare
- name: create deploy directories
  file: path={{ item }} state=directory owner={{ ratel_user }} group={{ ratel_user }} mode=0755
  with_items:
  - "{{ ratel_log_dir }}"

# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"
