---

- name: stop alpha
  systemd: name=alpha-{{ alpha_port }} state=stopped daemon_reload=yes enabled=yes

- name: wait for service port is down
  wait_for:
    port: "{{ alpha_port }}"
    state: stopped
    msg: "the service port {{ alpha_port }} is not down"

