---

# get images state
- name: generate images info file without state
  template: src=images_info.yml.j2 dest={{ local_conf_dir }}/images_info.yml

- name: load images_info without state
  include_vars: file={{ local_conf_dir }}/images_info.yml

- name: check image tar file exists
  stat:
    path:  "{{ local_download_dir }}/{{ item.name }}.tar"
  with_items: "{{ images_info }}"
  register: "image_tar_st"

- name: generate images info file with state
  template: src=images_info.yml.j2 dest={{ local_conf_dir }}/images_info.yml

# get images
- name: load images_info with state
  include_vars: file={{ local_conf_dir }}/images_info.yml

- block:
    - name: get images
      import_role:
        name: docker_image
  when: "'exist: false' in images_info | to_yaml"

