---

# prepare
- name: create downloads and resources directories
  file: "path={{ item }} state=directory owner={{ deploy_user }} group={{ deploy_user }} mode=0755"
  with_items:
  - "{{ local_download_dir }}"
  - "{{ local_resource_dir }}"
  - "{{ local_binary_dir }}"
  - "{{ local_conf_dir }}"

# package
- include_tasks: "package.yml"

# image
- include_tasks: "image.yml"
