---

## check internal network
- name: detect internal network
  shell: >
    warn=no
    curl -s --connect-timeout 10 www.baidu.com 2>/dev/null >/dev/null; echo $?
  changed_when: false
  register: internal_network_st

- name: set internal network fact
  set_fact: has_internal_network={{ internal_network_st.stdout.strip() == '0' }}

- name: exit when not has internal network
  fail:
    msg: "The Control Machine must have access to the Internet in order to download related packages."
  when: not has_internal_network

## check external network
- name: detect external network
  shell: >
    warn=no
    curl -s --connect-timeout 10 google.com 2>/dev/null >/dev/null; echo $?
  changed_when: false
  register: external_network_st

- name: set external network fact
  set_fact: has_external_network={{ external_network_st.stdout.strip() == '0' }}

