---

# download packages
- include_vars: file={{ local_conf_dir }}/packages_info.yml

- name: download package packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ local_download_dir }}/{{ item.name }}.{{ item.type }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    checksum: "{{ item.checksum | default(omit) }}"
    force: yes
    validate_certs: no
  register: get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 4
  delay: "{{ 5 | random + 3 }}"
  when: has_internal_network and not item.exist
  with_items: "{{ packages_info }}"

