---

- name: generate init sql file
  template: src=init.sql.j2 dest={{ init_conf_dir }}/init.sql owner=root  group=root mode=0644

- name: execute init sql file
  shell: |
    mysql -u{{ root_user }} -p{{ root_pass }} < {{ init_conf_dir }}/init.sql
  args:
    executable: /bin/bash
