---

# get archives state
- name: generate archives info file without state
  template: src={{ src_pkgs_file_name | default('../templates/archives_info.yml.j2') }} dest={{ local_conf_dir }}/{{ dest_pkgs_file_name |  default('archives_info.yml') }}

- include_vars: file={{ local_conf_dir }}/{{ dest_pkgs_file_name |  default('archives_info.yml') }}

- name: check archive file exists
  stat:
    path:  "{{ local_download_dir }}/{{ item.name }}.{{ pkgs_file_suffix | default('tar.gz') }}"
  with_items: "{{ archives_info }}"
  register: "archive_file_st"

- name: generate archives state file with state
  template: src={{ src_pkgs_file_name | default('../templates/archives_info.yml.j2') }} dest={{ local_conf_dir }}/{{ dest_pkgs_file_name |  default('archives_info.yml') }}


# download archives
- include_vars: file={{ local_conf_dir }}/{{ dest_pkgs_file_name |  default('archives_info.yml') }}

- name: download archive archives
  get_url:
    url: "{{ item.url }}"
    dest: "{{ local_download_dir }}/{{ item.name }}.{{ pkgs_file_suffix | default('tar.gz') }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    checksum: "{{ item.checksum | default(omit) }}"
    force: yes
    validate_certs: no
  register: get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 4
  delay: "{{ 5 | random + 3 }}"
  with_items: "{{ archives_info }}"
  when: has_internal_network and not item.state
