---

- name: stop alpha
  systemd: name=alpha-{{ alpha_port }} state=stopped enabled=no

- name: delete start/stop script
  file: path={{ deploy_dir }}/script/{{ item }}_alpha_{{ alpha_port }}.sh state=absent
  with_items:
    - start
    - stop

- name: delete systemd service configuration
  file: path=/etc/systemd/system/alpha-{{ alpha_port }}.service state=absent

- name: delete run script
  file: path={{ script_dir }}/run_alpha_{{ alpha_port }}.sh state=absent

- name: delete configuration file
  file: path={{ item }} state=absent
  with_items:
  - "{{ alpha_conf_dir }}/{{ alpha_conf_filename }}"
  - "{{ alpha_conf_dir }}/{{ alpha_log_filename }}"
  - "{{ alpha_data_dir }}"

