---

# stop agent
- name: stop cloudera-scm-agent
  systemd: name=cloudera-scm-agent state=stopped

- name: wait until the cm-agent port is down
  wait_for:
    port: 9001
    state: stopped
    msg: "the cm-agent port 9001 is not down"
