---

# prepare
- name: create deploy directories
  file: path={{ item }} state=directory owner={{ init_user }} group={{ init_user }} mode=0755
  with_items:
  - "{{ init_conf_dir }}"

# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"

# configure
- include_tasks: "configure.yml"

# init
- name: kubeadm init
  shell: "kubeadm init --config {{ init_conf_dir }}/kubeadm-config.yml"
