---

- name: "add apt key from keyurl"
  apt_key:
    url: "{{ item.key_url }}"
    state: present
  with_items: "{{ service_infos }}"
  when: item.enable and item.key_url is defined

- name: "add apt key from keyserver"
  apt_key:
    keyserver: "{{ item.key_server }}"
    id: "{{ item.key_id }}"
  with_items: "{{ service_infos }}"
  when: item.enable and item.key_server is defined

- name: "add service repo"
  template: src=service_sources.list.j2 dest={{ apt_conf_dir }}/sources.list.d/{{ item.name }}.list owner={{ apt_user }} group={{ apt_user }} mode=0644 backup=yes
  with_items: "{{ service_infos }}"
  when: item.enable
