---

- name: copy packages
  copy: src={{ local_download_dir }}/{{ item }} dest={{ image_dir }} owner={{ rabbitmq_user }} group={{ rabbitmq_user }} mode=0644
  loop: "{{ dpkg_packages }}"

- name: install packages
  shell: "apt-get install -y ./*.deb"
  args:
    chdir: "{{ image_dir }}"
