---

- name: stop rabbitmq
  hosts: rabbitmq_node
  gather_facts: False
  any_errors_fatal: true
  tasks:
    - name: stop rabbitmq-server
      systemd:
        name: rabbitmq-server
        state: stopped
        enabled: no

- name: stop epmd
  hosts: rabbitmq_node
  gather_facts: False
  any_errors_fatal: true
  tasks:
    - name: stop epmd
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
      - epmd
      - epmd.socket
