---

- name: populate service facts
  service_facts:

- name: ensure mysql stopped
  systemd: name=mysql state=stopped
  when: "'mysql.service' in services"

- name: remove data
  shell: |
    backup_time=$(date +%Y%m%dT%H%M%S)
    if [[ -d {{ mysql_data_dir }}  ]]; then
      mv {{ mysql_data_dir }} {{ backup_dir }}/mysql-${backup_time}
    fi
    if [[ -d {{ mysql_conf_dir }} ]]; then
      mv {{ mysql_conf_dir }} {{ backup_dir }}/mysql-cnf-${backup_time}
    fi
  args:
    executable: /bin/bash

- name: remove mysql packages
  shell: |
    DEBIAN_FRONTEND=noninteractive apt-get purge -y mysql-*
  when: "'mysql.service' in services"

