---

- name: create configuration file
  template: src=redis-shake_{{ redis_shake_run_type }}.conf.j2 dest={{ redis_shake_conf_dir }}/{{ redis_shake_conf_filename }} owner={{ redis_shake_user }}  group={{ redis_shake_user }} mode=0644 backup=yes
  notify: reload redis-shake
