---

# prepare
- name: create deploy directories
  file: path={{ item }} state=directory owner={{ redis_shake_user }} group={{ redis_shake_user }} mode=0755
  with_items:
  - "{{ redis_shake_conf_dir }}"
  - "{{ redis_shake_log_dir }}"
  - "{{ redis_shake_data_dir }}"


# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"

# configure
- include_tasks: "configure.yml"
