---

- name: deploy systemd
  include_role:
    name: systemd
  vars:
    this_role_name: "xbstream_server_{{ xbstream_server_port }}"
    service_name: "xbstream_server-{{ xbstream_server_port }}"
    service_type: "{{ deployment_method }}" 
    deploy_user: root
