---

- name: stop mysql
  systemd: name=mysql state=stopped

- name: rm data
  file: path={{ mysql_data_dir }} state=absent

- name: create configuration file
  template: src=my.cnf.j2 dest={{ mysql_conf_dir }}/{{ mysql_conf_filename }} owner=root  group=root mode=0644 backup=yes
  notify: restart mysql
  changed_when: true

- name: restart mysql
  meta: flush_handlers
