---

local_download_dir: "{{ playbook_dir }}/download"
local_resource_dir: "{{ playbook_dir }}/resource"
local_binary_dir: "{{ playbook_dir }}/resource/bin"
local_conf_dir: "{{ playbook_dir }}/conf"

# names
package_names:
  - redis
  - redis_shake

image_names:

# urls
package_urls:
  - "http://download.redis.io/releases/redis-5.0.4.tar.gz"
  - "https://github.com/alibaba/RedisShake/releases/download/release-v2.0.3-20200724/redis-shake-v2.0.3.tar.gz"

image_repos:

# versions
package_versions:
  - 5.0.4
  - v2.0.3

image_tags:

# type 
package_types:
  - tar.gz
  - tar.gz

