
---

# ensure python docker module  installed
- include_role: 
    name: pip
  vars:
  - pip_version: pip3
    python_modules:
      - 'docker'

# load images
- include_vars: file={{ local_conf_dir }}/images_info.yml

- name: deploy image
  copy: "src={{ local_download_dir }}/{{ item }}.tar dest={{ image_dir }}/ owner={{ deploy_user }} group={{ deploy_user }} mode=0755"
  loop: "{{ image_names }}"

- name: load docker image from archive
  docker_image:
    state: present
    force: yes
    name: "{{ item.repository }}"
    tag: "{{ item.tag }}"
    load_path: "{{ image_dir }}/{{ item.name }}.tar"
  with_items: "{{ images_info }}"
  when: item.name in image_names

# generate manifest file
- name: generate kube-vip manifest file
  shell: |
    sudo docker run -it --rm plndr/kube-vip:{{ kube_vip_version }} /kube-vip sample manifest \
    | sed "s|plndr/kube-vip:'|plndr/kube-vip:{{ kube_vip_version }}'|" \
    | sudo tee /etc/kubernetes/manifests/kube-vip.yaml
