---

- name: create configuration file
  template: src=haproxy.cfg.j2 dest={{ haproxy_conf_dir }}/{{ haproxy_conf_filename }} owner={{ haproxy_user }} group={{ haproxy_user }} mode=0644 backup=yes
  notify: restart haproxy
