---

# prepare
- name: create deploy directories
  file: path={{ item }} state=directory owner={{ haproxy_user }} group={{ haproxy_user }} mode=0755
  with_items:
  - "{{ haproxy_conf_dir }}"

# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"

# configure
- include_tasks: "configure.yml"
