---

- name: copy packages
  copy: src={{ local_download_dir }}/{{ item }} dest={{ image_dir }} owner={{ erlang_user }} group={{ erlang_user }} mode=0755
  loop: "{{ dpkg_packages }}"

- name: install packages
  shell: "apt-get install -y ./*.deb"
  args:
    chdir: "{{ image_dir }}"
