---

- name: create configuration file
  copy: content={{ lookup('template', 'daemon.json.j2') | to_json }} dest={{ docker_conf_dir }}/{{ docker_conf_filename }} owner={{ docker_user }} group={{ docker_user }} mode=0644 backup=yes
  # template: src=daemon.json.j2 dest={{ docker_conf_dir }}/{{ docker_conf_filename }} owner={{ docker_user }} group={{ docker_user }} mode=0644 backup=yes
