---

# ensure docker installed
- include_role:
    name: docker

# ensure python docker module  installed
- include_role:
    name: pip
  vars:
  - python_modules:
      - 'docker'

# download image
- include_vars: file={{ local_conf_dir }}/images_info.yml

- name: download docker images
  docker_image:
    name: "{{ item.repository }}"
    tag: "{{ item.tag }}"
    archive_path: "{{ local_download_dir }}/{{ item.name }}.tar"
  when: has_internal_network and not item.exist
  with_items: "{{ images_info }}"

