---

- name: create configuration file
  template: src=xbstream.conf.j2 dest={{ xbstream_conf_dir }}/{{ xbstream_conf_filename }} owner={{ xbstream_user }}  group={{ xbstream_user }} mode=0644 backup=yes
  notify: restart xbstream
