---

- name: copy packages
  copy: src={{ local_download_dir }}/{{ item }}.deb dest={{ image_dir }} owner={{ deploy_user }} group={{ deploy_user }} mode=0755
  loop: "{{ dpkg_packages }}"

- name: install packages
  shell: "apt-get install -y ./proxysql.deb"
  args:
    chdir: "{{ image_dir }}"

- name: start proxysql
  systemd: name=proxysql state=started daemon_reload=yes enabled=yes
