---

# prepare
- name: create deploy directories
  file: path={{ item }} state=directory owner={{ docker_user }} group={{ docker_user }} mode=0755
  with_items:
  - "{{ docker_conf_dir }}"

# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"

# configure
- include_tasks: "configure.yml"

# restart
- name: restart docker
  systemd: name=docker state=restarted daemon_reload=yes enabled=yes

# user
- name: add deploy user to docker group
  user: name={{ deploy_user }} groups=docker append=yes
