---

- name: unarchive binary packages
  unarchive:
    src: "{{ local_download_dir }}/{{ item }}.tar.gz"
    dest: "{{ dgraph_bin_dir }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  loop: "{{ binary_names }}"
