---

# prepare
- name: create deploy directories
  file: path={{ item }} state=directory owner={{ dgraph_user }} group={{ dgraph_user }} mode=0755
  with_items:
  - "{{ dgraph_bin_dir }}"

# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"
