---

- name: deploy kubernetes node
  hosts: kube_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: docker }
    - { role: kube_pkg }
    - { role: haproxy }

- name: join master
  hosts: kube_master[1:]
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: master }

- name: join worker
  hosts: kube_worker
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: worker }

- name: deploy client
  hosts: kube_client
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: client }

