---

- name: reset node env
  hosts: kube_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: reset }

- name: reset node env
  hosts: kube_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: uninstall }

