---

- name: deploy redis
  hosts: redis_nodes
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: common_dir }
    - { role: redis }

- name: create redis instance
  hosts: redis_cluster
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: instance }

