--- 

# get kubectl config to localhost
- name: get kubectl config file from master
  fetch: 
    src: /etc/kubernetes/admin.conf
    dest: "{{ local_conf_dir }}/kubernetes_admin.conf"
    flat: yes
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: true

# put kubectl config to remote
- name: copy kubectl config file
  copy: src={{ local_conf_dir }}/kubernetes_admin.conf dest={{ client_conf_dir }}/config owner={{ client_user }} group={{ client_user }} mode=0600

- name: create kubectl completion bash file
  copy: src=kubectl.sh dest=/etc/profile.d/
