---

- name: rollback dnsmasq addn hosts file
  command: mv {{ backup_dir }}/{{ dnsmasq_addn_hosts_st.backup_file.split('/')[-1] }} {{ dnsmasq_conf_dir }}/{{ dnsmasq_addn_hosts_name }}
  when: dnsmasq_addn_hosts_st.changed and dnsmasq_addn_hosts_st.backup_file is defined

- name: rollback configuration file
  command: mv {{ backup_dir }}/{{ dnsmasq_conf_st.backup_file.split('/')[-1] }} {{ dnsmasq_conf_dir }}/{{ dnsmasq_conf_filename }}
  when: dnsmasq_conf_st.changed and dnsmasq_conf_st.backup_file is defined

- include_tasks: "restart.yml"

- name: update result
  fail:
    msg: update dnsmasq failed
