---

# systemd configuration generation
- name: create systemd service configuration
  template: "src=systemd_{{ service_type }}.service.j2 dest=/etc/systemd/system/{{ service_name }}.service mode=0644"

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: create start/stop script
  become: true
  template:
    src: "{{ item }}_role.sh.j2"
    dest: "{{ deploy_dir }}/script/{{ item }}_{{ this_role_name }}.sh"
    mode: "0755"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  with_items:
    - start
    - stop
