---


flannel_user: "{{ deploy_user }}"
flannel_conf_dir: "/etc/kubernetes/"
flannel_conf_filename: "kube-flannel.yml"

# flannel config
# You can choose what type of flannel backend to use
# please refer to flannel's docs : https://github.com/coreos/flannel/blob/master/README.md
flannel_backend_type: "vxlan"
flannel_vxlan_vni: 1
flannel_vxlan_port: 8472

# Limits for apps
flannel_memory_limit: 500M
flannel_cpu_limit: 300m
flannel_memory_requests: 64M
flannel_cpu_requests: 150m
