---

- name: create configuration file
  template: src=redis_{{ redis_mode }}.conf.j2 dest={{ instance_conf_dir }}/{{ instance_conf_filename }} owner={{ instance_user }}  group={{ instance_user }} mode=0644 backup=yes

