---

- name: deploy systemd
  include_role:
    name: systemd
  vars:
    this_role_name: "redis_{{ instance_port }}"
    service_name: "redis-{{ instance_port }}"
    service_type: "{{ deployment_method }}" 
