---

# stop docker
- name: stop docker
  systemd: name=docker state=stopped

# change dir
- name: change data and log dir
  script: change_dir.sh

# start docker
- name: start docker
  systemd: name=docker state=started
