---

- name: add proxysql backend
  hosts: proxysql_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name:
      shell: |
        mysql -uadmin -padmin -h 127.0.0.1 -P6032 --default-auth=mysql_native_password -e"
          INSERT INTO mysql_servers
          (hostgroup_id,hostname,port)
          VALUES 
          ({{ proxysql_hostgroup_id }},'{{ hostvars[groups['mysql_node'][-1]].inventory_hostname_short }}',{{ proxysql_mysql_port }});

          load mysql servers to runtime;
          save mysql servers to disk;
        "
      args:
        executable: /bin/bash
