---

- name: check deploy env
  hosts: mysql_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: check }
  tags:
    - check

- name: deploy mysql
  hosts: mysql_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: mysql }
    - { role: xtrabackup }
  tags:
    - mysql

- name: setup secondery instance
  hosts: mysql_node[1:]
  serial: 1
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: xbstream_client_cloud }
    - { role: xbstream_server }
  tags:
    - secondery

