---

- name: deploy cloudera manager parcel
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: cm_parcel }

- name: deploy cloudera manager database
  hosts: cm_database_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: mysql }
    - { role: init_mysql }

- name: deploy cloudera manager server
  hosts: cm_server_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: cm_server }

- name: deploy cloudera manager agent
  hosts: cm_agent_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: cm_agent }

- name: setup cloudera manager web env
  hosts: cm_server_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: cm_web }

- name: setup cloudera manager web env
  hosts: cm_server_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: cdh }
