---

- name: set cm api
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
  - name: get cloudera manager api version
    uri:
      url: http://{{ cloudera_management_server_host }}:{{ cloudera_management_web_port }}/api/version
      method: GET
      status_code: 200
      user: "{{ cloudera_management_default_user }}"
      password: "{{ cloudera_management_default_pass }}"
      force_basic_auth: yes
      return_content: yes
    register: api_version

  - name: set base cm api url
    set_fact:
      cm_api_url: "http://{{ cloudera_management_server_host }}:{{ cloudera_management_web_port }}/api/{{ api_version.content }}"

- name: stop cdh
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
  - name: stop cdh cluster
    uri:
      method: POST
      url: "{{ cm_api_url }}/clusters/CyTestCluster/commands/stop"
      user: "{{ cloudera_management_default_user }}"
      password: "{{ cloudera_management_default_pass }}"
    register: "http_result"

  - name: "wait cdh stopped"
    uri:
      method: GET
      url: "{{ cm_api_url }}/commands/{{ http_result.json.id }}"
      user: "{{ cloudera_management_default_user }}"
      password: "{{ cloudera_management_default_pass }}"
    register: "start_status"
    until: "start_status.json.active == false"
    retries: 12
    delay: 10

- name: stop mgmt
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
  - name: stop mgmt service
    uri:
      method: POST
      url: "{{ cm_api_url }}/cm/service/commands/stop"
      user: "{{ cloudera_management_default_user }}"
      password: "{{ cloudera_management_default_pass }}"
    register: "http_result"

  - name: "wait mgmt service stopped"
    uri:
      method: GET
      url: "{{ cm_api_url }}/commands/{{ http_result.json.id }}"
      user: "{{ cloudera_management_default_user }}"
      password: "{{ cloudera_management_default_pass }}"
    register: "start_status"
    until: "start_status.json.active == false"
    retries: 12
    delay: 10


- name: stop cm agent
  hosts: cm_agent_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
  - name: stop cm agent
    systemd:
      name: supervisord
      state: stopped
      enabled: no

  - name: wait cm agent port is down
    wait_for:
      port: 9001
      state: stopped
      msg: "the cm-agent port 9001 is not down"

- name: stop cm server
  hosts: cm_server_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
  - name: stop cm server
    systemd: 
      name: cloudera-scm-server
      state: stopped
      enabled: no

  - name: wait cm web port is down
    wait_for:
      port: 7180
      state: stopped
      msg: "the cm web port 7180 is not down"

- name: stop cm repo
  hosts: cm_repo_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
  - name: stop cm repo
    systemd: 
      name: cm_parcel-8000
      state: stopped
      enabled: no

  - name: wait until the cm-db port is down
    wait_for:
      port: 8000
      state: stopped
      msg: "the cm repo port 8000 is not down"


- name: stop cm db
  hosts: cm_database_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
  - name: stop cm db
    systemd: 
      name: cm_db-6603
      state: stopped
      enabled: no

  - name: wait cm db port is down
    wait_for:
      port: 6603
      state: stopped
      msg: "the cm db port 6603 is not down"
