---

- name: copy packages
  copy: src={{ local_download_dir }}/{{ item }} dest={{ image_dir }} owner={{ deploy_user }} group={{ deploy_user }} mode=0644
  loop: "{{ dpkg_packages }}"

- name: install packages
  shell: "apt-get install -y ./{{ item }}"
  args:
    chdir: "{{ image_dir }}"
  loop: "{{ dpkg_packages }}"
