---

# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"

# join
- name: get join command
  shell: kubeadm token create --print-join-command
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: true
  register: join_command_st

- name: kubeadm join
  shell: "{{ join_command_st.stdout.strip() }}"
