---
  
- block:
    - name: restart zero
      systemd: name=zero-{{ zero_port }} state=restarted
    - name: wait for zero port up
      wait_for:
        port: "{{ zero_port }}"
        state: started
        msg: "the zero port {{ zero_port }} is not up" 
        timeout: 60
  when: zero_conf_st.changed
  rescue:
    - include_tasks: "rollback.yml"

