---

# get packages state
- name: generate packages info file without state
  template: src=packages_info.yml.j2 dest={{ local_conf_dir }}/packages_info.yml

- name: load packages_info without state
  include_vars: file={{ local_conf_dir }}/packages_info.yml

- name: check package tar file exists
  stat:
    path:  "{{ local_download_dir }}/{{ item.name }}.{{ item.type }}"
  with_items: "{{ packages_info }}"
  register: "package_tar_st"

- name: generate packages info file with state
  template: src=packages_info.yml.j2 dest={{ local_conf_dir }}/packages_info.yml

# get packages
- name: load packages_info with state
  include_vars: file={{ local_conf_dir }}/packages_info.yml

- block:
    - name: get packages 
      import_role: 
        name: get_url
  when: "'exist: false' in packages_info | to_yaml"

