---

# prepare
- name: create deploy directories
  file: path={{ item }} state=directory owner={{ alpha_user }} group={{ alpha_user }} mode=0755
  with_items:
  - "{{ alpha_conf_dir }}"
  - "{{ alpha_log_dir }}"
  - "{{ alpha_data_dir }}"

# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"

# configure
- include_tasks: "configure.yml"
