---

- name: add admin user
  shell: |
    rabbitmqctl delete_user guest
    rabbitmqctl add_user {{ admin_user }} {{ admin_pass }}
    rabbitmqctl set_user_tags {{ admin_user }} administrator
    rabbitmqctl set_permissions --vhost / {{ admin_user }} '.*' '.*' '.*'
