---

docker_user: root
docker_conf_dir: /etc/docker/
docker_conf_filename: daemon.json

deployment_method: apt

# apt configs
service_apt_enable: True
docker_enable: True
apt_packages:
  - docker-ce=18.06.3~ce~3-0~ubuntu

# docker config
dns: "{{ docker_dns }}"
registry_mirrors: "{{ docker_registry_mirrors }}"
insecure_registries: "{{ docker_insecure_registries | default(False) }}"
