---
  
- block:
    - name: restart redis
      systemd: name=redis-{{ instance_port }} state=restarted
    - name: wait for redis port up
      wait_for:
        port: "{{ instance_port }}"
        state: started
        msg: "the redis port {{ instance_port }} is not up" 
  when: redis_conf_st.changed
  rescue:
    - include_tasks: "rollback.yml"

