---

rabbitmq_user: "{{ deploy_user }}"
rabbitmq_conf_dir: "/etc/rabbitmq"
rabbitmq_conf_emv_file: "rabbitmq-env.conf"

deployment_method: dpkg

# dpkg config
dpkg_packages:
  - rabbitmq-server_3.7.26-1_all.deb

# rabbitmq conf env
nodename: "{{ rabbitmq_nodename }}"
