---

local_conf_dir: "{{ playbook_dir }}/conf"

rabbitmq_user: "{{ deploy_user }}"
rabbitmq_conf_dir: "/etc/rabbitmq"
rabbitmq_conf_emv_file: "rabbitmq-env.conf"

deployment_method: dpkg

# dpkg config
dpkg_packages:
  - rabbitmq-server

# rabbitmq conf env
nodename: "{{ rabbitmq_nodename }}"

