---

- name: deploy dnsmasq
  hosts: dnsmasq_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: dnsmasq }

- name: deploy client
  hosts: client_node
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: client }
