---

- name: stop dnsmasq
  hosts: dnsmasq_node
  gather_facts: False
  any_errors_fatal: true
  tasks:
    - name: stop dnsmasq
      systemd:
        name: "dnsmasq"
        state: stopped
        enabled: no
