---

# deployment
- include_tasks: "{{ deployment_method }}_deployment.yml"

# join
- name: get join command
  shell: kubeadm token create --print-join-command
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: true
  register: join_command_st

- name: get certs token
  shell: kubeadm init phase upload-certs --upload-certs | tail -1
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: true
  register: certs_token_st

- name: kubeadm join
  shell: |
    {{ join_command_st.stdout.strip() }} \
    --certificate-key {{ certs_token_st.stdout.strip() }} \
    --control-plane \
    --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests
  register: join_result
  until: "'Initial timeout' not in join_result.stdout"
  retries: 3
  delay: 45
  failed_when: "'Initial timeout' in join_result.stdout"
